version: "3"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        networks:
            - broker-kafka
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        networks:
            - broker-kafka
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        container_name: kafdrop
        networks:
            - broker-kafka
        depends_on:
            - kafka
        ports:
            - 19000:9000
        environment:
            KAFKA_BROKERCONNECT: kafka:29092

    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: certificate
        ports:
            - 27017:27017
        volumes:
            - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
        networks:
            - mongo-compose-network

    rabbitmq:
        image: "rabbitmq:3.8-management-alpine"
        container_name: rabbitmq
        hostname: localhost
        ports:
            - 15672:15672
            - 5672:5672
        volumes:
            - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin

networks:
    broker-kafka:
        driver: bridge
    mongo-compose-network:
        driver: bridge
    rabbitmq_go_net:
        driver: bridge
